import React, { useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { api, getAccessToken } from "../lib/api";
import { EmptyState, Screen, SectionTitle, StatusPill } from "../components/ui";

export default function ChamaFeedScreen() {
  const [feed, setFeed] = useState(null); const [loading, setLoading] = useState(true);
  const load = async () => { if (!getAccessToken()) { setLoading(false); return; } setLoading(true); try { setFeed(await api.groups.feed()); } catch (error) { Alert.alert("Could not load Chama Hub", error.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const rsvp = async (id, response) => { try { await api.groups.rsvp(id, response); await load(); } catch (error) { Alert.alert("RSVP failed", error.message); } };
  if (loading) return <View className="flex-1 items-center justify-center bg-[#F6F8FB]"><ActivityIndicator color="#059669" /></View>;
  if (!getAccessToken()) return <Screen className="items-center justify-center p-8"><Ionicons name="lock-closed-outline" size={32} color="#94a3b8" /><Text className="text-slate-500 mt-3 text-center">Sign in on the Today tab to use Chama Hub.</Text></Screen>;
  return <Screen><ScrollView contentContainerClassName="pb-10"><View className="bg-emerald-950 px-5 pt-16 pb-12 rounded-b-[36px]"><View className="flex-row justify-between"><View><Text className="text-emerald-300 text-[10px] font-black uppercase tracking-[2px]">Collective planning</Text><Text className="text-white text-3xl font-black mt-2">Chama Hub</Text></View><View className="h-12 w-12 bg-white/10 rounded-2xl items-center justify-center"><Ionicons name="people" size={22} color="#a7f3d0" /></View></View><Text className="text-emerald-100 mt-3 leading-5">Shared events, invitations and contribution goals in one calm workspace.</Text></View><View className="px-4 -mt-5">
    {!!feed?.invitations?.length && <View className="mb-7"><SectionTitle eyebrow="Needs your answer" title="Invitations" />{feed.invitations.map((invite) => <View key={invite.id} className="bg-white rounded-[26px] border border-amber-100 p-5 mb-3"><View className="flex-row justify-between"><View className="flex-1"><StatusPill label={invite.group.name} tone="amber" /><Text className="text-slate-950 text-lg font-black mt-3">{invite.event?.title || "Join this group"}</Text></View><Ionicons name="mail-unread-outline" size={21} color="#d97706" /></View><View className="flex-row gap-2 mt-5"><TouchableOpacity onPress={() => rsvp(invite.id, "DECLINED")} className="flex-1 bg-slate-100 py-3 rounded-xl items-center"><Text className="font-bold text-slate-600">Decline</Text></TouchableOpacity><TouchableOpacity onPress={() => rsvp(invite.id, "ACCEPTED")} className="flex-1 bg-emerald-500 py-3 rounded-xl items-center"><Text className="font-black text-emerald-950">Accept</Text></TouchableOpacity></View></View>)}</View>}
    <View className="mt-8"><SectionTitle eyebrow="Your circles" title="Groups" action="Create group" />{feed?.groups?.length ? feed.groups.map((group) => { const percentage = group.targetAmount ? Math.min(100, Math.round((Number(group.currentAmount) / Number(group.targetAmount)) * 100)) : 0; return <View key={group.id} className="bg-white rounded-[26px] border border-slate-100 p-5 mb-3"><View className="flex-row justify-between"><View><Text className="text-slate-950 font-black text-base">{group.name}</Text><Text className="text-slate-500 text-xs mt-1">{group._count.members} members</Text></View><StatusPill label="Active" tone="emerald" /></View><View className="mt-5"><View className="flex-row justify-between mb-2"><Text className="text-slate-700 font-bold">KSh {Number(group.currentAmount).toLocaleString()}</Text><Text className="text-slate-400 text-xs">{group.targetAmount ? `of KSh ${Number(group.targetAmount).toLocaleString()}` : "No target set"}</Text></View><View className="h-2 bg-slate-100 rounded-full overflow-hidden"><View style={{ width: `${percentage}%` }} className="h-2 bg-emerald-500 rounded-full" /></View></View></View>; }) : <EmptyState icon="people-outline" title="Bring your people together" description="Create a circle for shared events, invites, and contribution goals." action="Create your first group" />}</View><View className="mx-1 mt-7 bg-slate-900 rounded-[28px] p-5"><Text className="text-emerald-300 text-[10px] font-black uppercase tracking-[2px]">Designed for trust</Text><Text className="text-white text-lg font-black mt-2">Every decision stays visible.</Text><Text className="text-slate-300 leading-5 mt-2">Member permissions, RSVP history, and contribution milestones will all live here.</Text></View></View></ScrollView></Screen>;
}
