import React, { useEffect, useState } from "react";
import { ScrollView, Switch, Text, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { clearSession, restoreSession } from "../lib/session";
import { Screen, SectionTitle, StatusPill } from "../components/ui";

const Row = ({ icon, title, detail, right }) => <View className="flex-row items-center py-4 border-b border-slate-100"><View className="h-10 w-10 rounded-xl bg-slate-100 items-center justify-center"><Ionicons name={icon} size={19} color="#334155" /></View><View className="ml-3 flex-1"><Text className="font-bold text-slate-800">{title}</Text>{detail ? <Text className="text-xs text-slate-500 mt-1">{detail}</Text> : null}</View>{right || <Ionicons name="chevron-forward" size={18} color="#94a3b8" />}</View>;
export default function SettingsScreen() {
  const [user, setUser] = useState(null); const [reminders, setReminders] = useState(true); const router = useRouter();
  useEffect(() => { restoreSession().then(setUser); }, []);
  const logout = async () => { await clearSession(); router.replace("/"); };
  return <Screen><ScrollView contentContainerClassName="px-4 pt-16 pb-10"><View className="flex-row items-center"><View className="h-14 w-14 rounded-2xl bg-emerald-500 items-center justify-center"><Text className="text-emerald-950 text-xl font-black">{user?.name?.slice(0, 1).toUpperCase() || "U"}</Text></View><View className="ml-4 flex-1"><Text className="text-slate-950 text-2xl font-black">{user?.name || "Your account"}</Text><Text className="text-slate-500 mt-1">{user?.phoneNumber || "Sign in to manage preferences"}</Text></View><StatusPill label="Staging" tone="amber" /></View><View className="mt-9"><SectionTitle eyebrow="Preferences" title="Make it yours" /><View className="bg-white rounded-[28px] px-5 border border-slate-100"><Row icon="notifications-outline" title="Event reminders" detail="15 minutes before" right={<Switch value={reminders} onValueChange={setReminders} trackColor={{ false: '#cbd5e1', true: '#6ee7b7' }} thumbColor="#fff" />} /><Row icon="time-outline" title="Timezone" detail="Africa/Nairobi" /><Row icon="language-outline" title="Language" detail="English" /></View></View><View className="mt-8"><SectionTitle eyebrow="Security" title="Account protection" /><View className="bg-white rounded-[28px] px-5 border border-slate-100"><Row icon="key-outline" title="Change password" /><Row icon="phone-portrait-outline" title="Phone verification" detail="Manage sign-in methods" /><Row icon="lock-closed-outline" title="Privacy controls" detail="Manage data and connected services" /></View></View><TouchableOpacity onPress={logout} className="mt-8 border border-rose-200 bg-rose-50 rounded-2xl py-4 flex-row justify-center items-center"><Ionicons name="log-out-outline" size={18} color="#be123c" /><Text className="text-rose-700 font-black ml-2">Sign out</Text></TouchableOpacity><Text className="text-center text-slate-400 text-xs mt-5">Regional Scheduler · Version 1.0.0</Text></ScrollView></Screen>;
}
